[tool.isort]
line_length = 120
force_grid_wrap = 2
src_paths = ["src"]

[tool.black]
line-length = 120
target-version = ['py312']

[tool.flake8]
exclude = [".git", ".tox", ".venv", "build", "dist", "*.egg-info", "*.egg", "env", "venv", ".env", ".git", "__pycache__"]
max-line-length = 120
max-complexity = 10
ignore = ["W291", "F401"]