---
title: Регистрация
config:
  theme: forest
---
sequenceDiagram
    autonumber

    actor U as User
    box transparent Сервер
        participant S as Server
        participant App as FastAPI
        participant DB as Database
    end

    
activate S

    U ->> S: Отправляет данные для регистрации
    Note over U,S: email = 'user@user.com'<br/>password = '123'

    S ->> App: Данные отправляются в route

    App --> DB: Устанавливает соединение
    App ->> DB: SELECT * FROM User WHERE email = 'user@user.com'
    Note over App,DB: Получаем все записи из таблицы с таким email

    DB ->> App: Возвращает записи

    alt БД вернула пустой список
        App ->> App: Хэширует пароль
        App ->> DB: Создай новую запись в таблице User
        Note over App, DB: id = 1, email = 'user@user.com', password: 'sXhsuxn7ysbX'
        DB ->> App: Возвращает созданную запись
        App ->> App: Формирует JSON<br/> {'id': 1, 'email': 'user@user.com'}
        App ->> S: Возвращает JSON
        S ->> U: Вернул 200 OK и JSON
    else БД вернула не пустой список
        App ->> S: HTTPException 409: Такой пользователь уже существует
        S ->> U: Вернул 409 и JSON с деталями ошибки
    end

deactivate S